version: "3"
services:
  issuer-wallet-db:
    image: postgres:11
    container_name: issuer-wallet-db
    command: postgres -c listen_addresses='*'
    # env file defines
    env_file:
      - .env
    # This creates the data base tables if not present. See resources/init.sql #
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - issuer
    tty: true
  issuer-agent:
    build:
      context: .
      dockerfile: dockerfiles/agent/Dockerfile.prod
    env_file:
      - .env
    ports:
      - 1020:3020
      - 1021:3021
    networks:
      - issuer
    volumes:
      - issuer-agent:/home/indy/.indy_client/wallet
  issuer-business-logic:
    build:
      context: .
      dockerfile: dockerfiles/service/Dockerfile.service
    depends_on:
      - issuer-agent
    networks:
      - issuer
    env_file:
      - .env
    ports:
      - 1010:3010
    entrypoint: /bin/bash
    command: [
      "-c",
      "python -u service/main.py;"
    ]
volumes:
  issuer-agent:
networks:
  issuer:
