version: "3"
services:
  issuer-agent:
    build:
      context: .
      dockerfile: dockerfiles/agent/Dockerfile.prod
    env_file:
      - .env
    ports:
      - 1020:3020
      - 1021:3021
    networks:
      - issuer
    volumes:
      - issuer-agent:/home/indy/.indy_client/wallet
  issuer-logic:
    build:
      context: .
      dockerfile: dockerfiles/service/Dockerfile.service
    depends_on:
      - issuer-agent
    networks:
      - issuer
    env_file:
      - .env
    ports:
      - 1010:3010
    entrypoint: /bin/bash
    command: [
      "-c",
      "python -u service/main.py;"
    ]
volumes:
  issuer-agent:
networks:
  issuer:
