version: "3"
services:
  ngrok-issuer:
    image: wernight/ngrok
    command: ngrok http issuer-agent:${ISSUER_HTTP_PORT} --log stdout
    networks:
      - issuer
  issuer-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      - NGROK_NAME=ngrok-issuer
      - ADMIN_URL=http://issuer-agent:${ISSUER_ADMIN_PORT}
      - AGENT_NAME=${ISSUER_AGENT_NAME}
      - ADMIN_PORT=${ISSUER_ADMIN_PORT}
      - HTTP_PORT=${ISSUER_HTTP_PORT}
      - WEBHOOK_URL=${ISSUER_WEBHOOK_URL}
      - AGENT_ENDPOINT=${ISSUER_AGENT_ENDPOINT}
      - WALLET_SEED=${ISSUER_WALLET_SEED}
      - WALLET_NAME=${ISSUER_WALLET_NAME}
      - WALLET_KEY=${ISSUER_WALLET_KEY}
      - WALLET_TYPE=${WALLET_TYPE}
      - ACAPY_ADMIN_INSECURE_MODE=${ISSUER_ADMIN_SECURE}
      - GENESIS_URL=${GENESIS_URL}
    ports:
      - ${ISSUER_HTTP_PORT}:${ISSUER_HTTP_PORT}
      - ${ISSUER_ADMIN_PORT}:${ISSUER_ADMIN_PORT}
    networks:
      - issuer
    volumes:
      - issuer-agent:/home/indy/.indy_client/wallet
  issuer-logic:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        - jupyter_port=${ISSUER_JUPYTER_PORT}
    depends_on:
      - issuer-agent
    networks:
      - issuer
    environment:
      WEBHOOK_HOST: 0.0.0.0
      ADMIN_URL: http://issuer-agent:${ISSUER_ADMIN_PORT}
      WEBHOOK_PORT: ${ISSUER_WEBHOOK_PORT}
    ports:
      - ${ISSUER_WEBHOOK_PORT}:${ISSUER_WEBHOOK_PORT}
    entrypoint: /bin/bash
    command: [
      "-c",
      "python -u service/main.py;"
    ]
volumes:
  issuer-agent:
networks:
  issuer:
