FROM python:3.6

# Set the working directory to /app
WORKDIR /service

# Copy the current directory contents into the container at /app
ADD . /service

ADD requirements.txt .
RUN pip install -r requirements.txt
