FROM python:3.8



# Install the aries_cloudcontroller

ADD requirements.txt requirements.txt

RUN pip install -r requirements.txt



# Set the working directory to /app
WORKDIR /service

# Copy the current directory contents into the container at /app
ADD service /service/service
